var config = {
	"socket":{
		"url":"https://my.fluentcloud.com",
		"socket":443,
		"secure":true,
		"transport":"websocket"
	},
	"authentication":{
		"url":"https://my.fluentcloud.com/api/v1/core/authenticate",
		"httpType":"GET",
		"maxAttempts":10
	},
	"ajax":{
		"apiNamespace":{
			"core":{
				"url":"https://my.fluentcloud.com/api/v1/core/"
			},
			"call":{
				"url":"https://my.fluentcloud.com/api/v1/call/"
			}
		}
	}
};
